config/routes.rb
Projtest::Application.routes.draw do
  get "sessions/new"
  get "users/new"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  resources :users
  resources :sessions
  resources :users do
    member do
      get :private_office
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password,:lastname, :login, :name, :password_confirmation, :avatar ,:byrthday,:phone_number
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                             :default_url => '/images/1.jpg'

  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password

  validates_presence_of :password, :on => :create

  validates :byrthday, :presence => true

  validates :phone_number, :presence => true, 
                    :length => {:minimum => 10, :maximum => 10}

  validates :email, :presence => true, 
                    :length => {:minimum => 3, :maximum => 254},
                    :uniqueness => true,
                    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  
  validates :login, :presence => true,
                    :length => { :maximum => 50 },
                    :uniqueness =>true
  
  validates :password,:length => { :maximum => 16,:minimum => 6 }, :on => :create

  validates :name, :presence => true,
                   :length => { :maximum => 50 }

  validates :lastname, :presence => true,
                       :length => { :maximum => 50 }

  
  def self.authenticate(login, password)
    user = find_by_login(login)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

 private

  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  user = User.authenticate(params[:login], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to user, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid login or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
  end

 def create
  @user = User.new(params[:user])
  if !@user.avatar
   @user.avatar="/images/1.jpg"
  end
  if @user.save
    redirect_to log_in_url, :notice => "Signed up!"
  else
    render "new"
  end
 end
 
 def show
    @user = User.find(params[:id])
    @title = @user.email
 end
 
 def update
  @user=User.find(session[:user_id]) if session[:user_id]
  @user.update_attributes(params[:user])
  redirect_to user_path
 end
 
 def private_office
  @user=current_user
 end
 
 def destroy
   User.find(params[:id]).destroy
   flash[:success] = "User destroyed."
   session[:user_id] = nil
   redirect_to root_url
 end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projtest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
   <div id="container">
   <div id="header"><ul>
      <% if current_user %>
       <%= link_to "Главная", user_path %>
       <%= link_to "Личный кабинет", private_office_user_path(@user)%>
       <%= link_to "Выйти", log_out_path %>
      <% else %>
       <%= link_to "Регистрация", sign_up_path %> or
       <%= link_to "Войти", log_in_path %>
      <% end %>
          </ul></div>

   <div id="content">
     
   </div>

  <div id="footer">&copy; Дмитрий С.</div>
  </div>
<%= yield %>
</body>
</html>

app/views/users/new.html.erb
<% if !current_user %>
<h1>Регистрация</h1>
<%= form_for  @user,  :html => { :multipart => true } do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :Логин %><br />
    <%= f.text_field :login %>
  </p>
  <p>
    <%= f.label :Имя %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Фамилия %><br />
    <%= f.text_field :lastname %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :Дата_рождения %><br />
    <%= f.text_field :byrthday %>
  </p>
  <p>
    <%= f.label :Телефон %><br />
    <%= f.text_field :phone_number %>
  </p>
  <p>
    <%= f.label :пароль %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :Подтверждение_пароля %><br />
    <%= f.password_field :password_confirmation %>
  </p>
   <%= f.file_field :avatar %>
  <p class="button"><%= f.submit %></p>
<% end %>
<% end %>

app/views/users/private_office.html.erb
<% if current_user %>
    Пользователь: <%= current_user.name %><%= current_user.lastname.first %>.</br>
    <%= form_for @user do |f| %>
  <p>
    <%= f.label :Имя %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Фамилия %><br />
    <%= f.text_field :lastname %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
   <p>
    <%= f.label :Дата_рождения %><br />
    <%= f.text_field :byrthday %>
  </p>
  <p>
    <%= f.label :Телефон %><br />
    <%= f.text_field :phone_number %>
  </p>
  <p>
   <%= f.file_field :avatar %>
  </p>
  <p class="button"><%= f.submit "Изменить"%></p>
<% end %> 
<%= button_to "Удалить", @user, :method=>:delete,:confirm => "Вы уверены?", :class=>:destroy %>

<% end %>

app/views/users/show.html.erb
<div id="content">
<% if current_user %>
    <%= image_tag current_user.avatar.url(:thumb) %></br>
    Пользователь: <%= current_user.name %><%= current_user.lastname.first %>.</br>
    Почта:<%= current_user.email%></br>
    Дата рождения:<%= current_user.byrthday%></br>
    Телефон:<%= number_to_phone(@user.phone_number, :area_code=>true)%>
<% end %>    
</div>